In [2]:
#Import necessary libraries for future use
import numpy as np
import pandas as pd

In [3]:
""" 
q1) Write a Python/NumPy code block that finds the distinct/unique common items between these two arrays:
        
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.
"""
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

x = set() #Create empty set

for i in range(len(a)): #Iterate through lists
  if a[i] == b[i]: #If the elements at the same index in both lists are equivalent
    x.add(a[i]) #Add them to the set. Only unique values will be stored.

print(x)

{2, 4}


In [26]:
"""
q2) Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.

1   6    11
2   7    12
3   8    13
4   9    14
5   10   15
"""

q2_list = [] #Create an empty list

for r in range(5): #Create 5 rows
  q2_list.append([]) #Append empty list to matrix
  for c in range(3): #Create 3 columns
    q2_list[r].append(((5 * c) + r) + 1) #Math to create appropriate value


for i in range(len(q2_list)): #Print matrix
  print(q2_list[i], " ")

[1, 6, 11]  
[2, 7, 12]  
[3, 8, 13]  
[4, 9, 14]  
[5, 10, 15]  


In [5]:
"""
q3) The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. 
Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 
1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
"""

q3_list = [] #Create empty list
for r in range(len(q2_list[r])): #Iterate through columns
  for c in range(len(q2_list)): #Iterate through rows
    q3_list.append(q2_list[c][r]) #Append in row major order

print(q3_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [23]:
"""
q4) Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, 
and the third column becomes the third dimension of the 3-D array.

Side Note: I'm not sure if I interpreted your instructions correctly here. When you say you want the first column to become the first dimension,
I assume you want it to become the first [5][1] block of 3.
"""

temp = np.array(q2_list)
q4_list = temp.reshape(3,5,1)
print(q4_list)

[[[ 1]
  [ 6]
  [11]
  [ 2]
  [ 7]]

 [[12]
  [ 3]
  [ 8]
  [13]
  [ 4]]

 [[ 9]
  [14]
  [ 5]
  [10]
  [15]]]  


In [30]:
# q5) Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.

q5_list = q4_list.reshape(5,3)
print(q5_list, " ")

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]  


In [ ]:
"""
# q6) You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.
"""
a = np.array([12, 5, 7, 15, 3, 1, 8]) #Given numpy arrays
b = np.array([14, 6, 3, 11, 19, 12, 5])
del_indices = [] #List to store the indices that will be deleted from list a
b_set = set() #A set to store the unique values in list b

for i in range(len(b)): #Iterate through list b
  b_set.add(b[i]) #Add unique elements of list b to set b_set

for i in range(len(a)): #Iterate through a
  if a[i] in b_set: #If the value stored at a[i] is in set b_set
    del_indices.append(i) #Add that index to del_indices. These indices will be deleted from list a.

print("Indices to be deleted", del_indices) #Print the indices that are to be deeted from list a
new_a = np.delete(a, del_indices) #Delete the aformentioned indices from list a and create a new list, new_a
print("a after deleting elements that appears in b:", new_a) #Print new_a which contains the values of a after the deletions took place

# Code inspired by https://stackoverflow.com/questions/10996140/how-to-remove-specific-elements-in-a-numpy-array

Indices to be deleted [0, 1, 4]
a after deleting elements that appears in b: [ 7 15  1  8]


In [ ]:
#Get Module6 data from github

df = pd.read_csv("https://raw.githubusercontent.com/espio11/Data-Analytics-Summer-2022/main/Module6_Data.txt", sep = "\t")
df.style.set_properties(**{'text-align': 'left'})
df.head()

Year  New York City Population  NYC Consumption(Million gallons per day)  \
0  1979                 7102100.0                                    1512.0   
1  1980                 7071639.0                                    1506.0   
2  1981                 7089241.0                                    1309.0   
3  1982                 7109105.0                                    1382.0   
4  1983                 7181224.0                                    1424.0   

   Per Capita(Gallons per person per day)  
0                                     213  
1                                     213  
2                                     185  
3                                     194  
4                                     198

In [ ]:
# q7.1) What is the maximum yearly NYC consumption of water in millions of gallons per day?

consumption = df["NYC Consumption(Million gallons per day)"] #Create list of NYC Consumption values

max_value = np.max(consumption) #Get max value from NYC Consumption list. Code from: https://pythonexamples.org/python-numpy-maximum-value-of-array/
print(max_value) #Print the max value

1512.0


In [ ]:
# q7.2) How many calendar years are represented within this data set? NumPy's shape command is one way to find out.

year_list = df["Year"] #Create list of Year values
year_count = len(year_list) #Get the length of year_list
print(year_count) #Print the count for year_list

39


In [ ]:
# q7.3) What is the mean and the standard deviation of the per capita daily water consumption?

capita_list = df["Per Capita(Gallons per person per day)"] #Create list of Per Capita(Gallons per person per day) values
print("Mean of Per Capita(Gallons per person per day) : ", np.mean(capita_list)) #Calculate and print the mean. Code from: https://www.geeksforgeeks.org/numpy-mean-in-python/
print("Standard Deviation of Per Capita(Gallons per person per day) : ", np.std(capita_list)) #Calculate and print Standard Deviation. Code from: https://www.geeksforgeeks.org/numpy-std-in-python/

Mean of Per Capita(Gallons per person per day) :  160.30769230769232
Standard Deviation of Per Capita(Gallons per person per day) :  31.51894330370624


In [ ]:
# q7.4) What is the increase or decrease in population from year to year? 
# Use NumPy's `diff` function to create an array of differences and save that to a variable called "pop_diff", then print that variable to the screen.

population_list = df["New York City Population"] #Create list of Year values
pop_diff = np.diff(population_list) #Create list of year value differences
print(pop_diff) #print list

[-30461.   17602.   19864.   72119.   53290.   39540.   45192.   23230.
  11243.   -9544.   -8525.   38851.   54443.   77222.   64292.   62582.
  64772.   75631.   84816.   89401.   60618.   16685.5  16685.5  16685.5
  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5  16685.5 108965.
  77081.   61281.   49530.   44512.   21171.   85025. ]
